# Generated by Django 3.1.3 on 2020-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('father', models.CharField(max_length=120)),
                ('mother', models.CharField(max_length=120)),
                ('roll', models.IntegerField(max_length=6, unique=True)),
                ('reg', models.IntegerField(max_length=8, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
