# Generated by Django 3.1.3 on 2020-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201125_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg',
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(max_length=6, unique=True),
        ),
    ]
