# Generated by Django 3.1.3 on 2020-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201125_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(upload_to='studentphoto'),
        ),
    ]
